import React from "react";
import { Box, Typography, useTheme } from "@mui/material";
import Header from "../../components/Header";
import Accordion from "@mui/material/Accordion";
import AccordionSummary from "@mui/material/AccordionSummary";
import AccordionDetails from "@mui/material/AccordionDetails";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import { tokens } from "../../theme";
const FAQ = () => {
  const theme = useTheme();
  const colors = tokens(theme.palette.mode);
  const list = [
    {
      question: "How can you be sure the numbers are really random?",
      answer: "Oddly enough, it is theoretically impossible to prove that a random number generator is really random. Rather, you analyse an increasing amount of numbers produced by a given generator, and depending on the results, your confidence in the generator increases (or decreases, as the case may be). This is explained in more detail on my Statistical Analysis page, which also contains two studies of the numbers generated by RANDOM.ORG, both of which concluded that the numbers are sound. In addition, the continually updated Real-Time Statistics page gives you an indication of the quality of the numbers produced over time.",
      id: "1",
    },
	{
		question: "Have the numbers been certified by an independent third party?",
		answer: "The numbers produced by RANDOM.ORG have been evaluated by eCOGRA, which is a non-profit regulatory body that acts as the independent standards authority of the online gaming industry. For a typical gambling site, eCOGRA will oversee many aspects of its operation, including financial aspects, such as payout percentages. RANDOM.ORG is not a gambling site, so in our case, eCOGRA only evaluated the quality of the random numbers. ",
		id: "2",
	  },
	  {
		question: "What are some random questions to ask?",
		answer: "That's exactly the reason we created this random question generator. There are hundreds of random questions to choose from so you're able to find the perfect random question to ask friends, family and people you want to get to know better.",
		id: "3",
	  },
	  {
		question: "How do I pick winners for a lottery or drawing?",
		answer: "Many people are using RANDOM.ORG for this purpose. Since March 2007, there is the Third-Party Draw Service, which is especially intended for holding drawings and which will keep records of the outcome. The records serve as evidence that the drawing was conducted fairly, in case someone should question it later on. See the Guide to Random Drawings and section 5 of this FAQ for further details. If you have no budget but a group of entrants who trust you, then you can use the Sequence Generator. In this case, RANDOM.ORG will not store a record of the result, so your entrants cannot verify the result. Let us assume you have sold or given out sequentially numbered lottery tickets",
		id: "4",
	  },
  ];
  return (
    <Box m="20px">
      <Header title="FAQ Page" subtitle="Frequently Asked Questions"></Header>
      <Box height="20px"></Box>
      {list.map((item) => (
        <Accordion key={item.id}>
          <AccordionSummary expandIcon={<ExpandMoreIcon />}>
            <Typography color={colors.greenAccent[500]} variant="h5">
              {item.question}
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography>
			{item.answer}
            </Typography>
          </AccordionDetails>
        </Accordion>
      ))}
    </Box>
  );
};

export default FAQ;
